"""System Architecture Schema — describes the full FLUX layer hierarchy."""

from __future__ import annotations
from typing import Optional

FLUX_ARCHITECTURE: dict = {
    "name": "FLUX",
    "version": "2.0",
    "description": (
        "Fluid Language Universal eXecution — agent-first, self-evolving runtime. "
        "A markdown-to-bytecode system with polyglot language mixing, "
        "adaptive optimization, tile-based computation, self-evolution, "
        "agent swarms, persistent memory, digital twin simulation, "
        "and creative expression."
    ),
    "layers": [
        {
            "id": "L0_PARSER",
            "name": "FLUX.MD Parser",
            "input": "FLUX.MD markdown",
            "output": "AST (parse tree)",
            "module": "flux.parser",
            "tests": "test_parser.py (11 tests)",
            "features": [
                "YAML frontmatter extraction",
                "Headings (h1-h6)",
                "Fenced code blocks with language tags",
                "Ordered/unordered lists",
                "Paragraphs",
                "Agent directives (## agent: / ## fn:)",
                "Source spans (line/column tracking)",
                "Code block classification (flux/data/native)",
            ],
        },
        {
            "id": "L0_FRONTEND",
            "name": "Language Frontends",
            "input": "C, Python source code",
            "output": "AST nodes / FIR module",
            "module": "flux.frontend",
            "tests": "test_frontends.py",
            "features": [
                "C frontend (parse -> AST -> FIR)",
                "Python frontend (parse -> AST -> FIR)",
                "Cross-language type mapping",
            ],
        },
        {
            "id": "L1_FIR",
            "name": "FIR (Flux Intermediate Representation)",
            "input": "AST",
            "output": "SSA-based FIR module",
            "module": "flux.fir",
            "tests": "test_fir.py (13 tests)",
            "features": [
                "SSA form (Static Single Assignment)",
                "15 immutable FIR types (i8-i128, f32/f64, bool, ptr, vec, func, struct, unit, void, string)",
                "TypeContext interning for canonical singletons",
                "42 instruction classes across 7 categories",
                "Basic blocks with terminators",
                "Control flow (branch, conditional, call, ret, jump)",
                "FIRBuilder ergonomic API",
                "Structural validator (4 invariants)",
                "Human-readable printer",
            ],
        },
        {
            "id": "L1_TYPES",
            "name": "Type System & Unification",
            "input": "C/Python/Rust type annotations",
            "output": "Unified FIR types",
            "module": "flux.types",
            "tests": "test_type_unify.py (76 tests)",
            "features": [
                "C type mapping (int/long/float/double/char/void/bool/pointer/struct/enum/const)",
                "Python type mapping (int/float/bool/str/None/list/dict)",
                "Rust type mapping (i8-i128/u8-u128/f32/f64/bool/String/Vec/Option/Result/HashMap/arrays/Box/tuple/ref)",
                "Bidirectional conversion (to_c/to_python/to_rust)",
                "Coercion cost model (0-100 scale)",
                "Type unification (LUB - least upper bound)",
                "Implicit coercion rules",
                "Generic types (TypeVar, GenericType, TypeScheme with forall quantification)",
                "Cross-language compatibility checking",
            ],
        },
        {
            "id": "L2_BYTECODE",
            "name": "FLUX Bytecode",
            "input": "FIR module",
            "output": "Binary bytecode (104 opcodes)",
            "module": "flux.bytecode",
            "tests": "test_bytecode.py (12 tests)",
            "features": [
                "104 opcodes across 11 categories",
                "Variable-length encoding (Formats A/B/C/D/E/G)",
                "Binary format: Header + Type Table + Name Pool + Function Table + Code Section",
                "18-byte header (FLUX magic, version, flags, func count, type/code offsets)",
                "SSA value -> register mapping (0x3F mask = 64 registers)",
                "BytecodeEncoder (FIR -> binary)",
                "BytecodeDecoder (binary -> DecodedModule)",
                "BytecodeValidator (structural checks)",
            ],
        },
        {
            "id": "L2_OPTIMIZER",
            "name": "Optimizer Passes",
            "input": "FIR module",
            "output": "Optimized FIR module",
            "module": "flux.optimizer",
            "tests": "test_optimizer.py",
            "features": [
                "Constant folding/propagation",
                "Dead code elimination",
                "Block layout optimization",
                "Function inlining",
                "Pipeline of passes",
            ],
        },
        {
            "id": "L2_JIT",
            "name": "JIT Compiler",
            "input": "Hot functions",
            "output": "Compiled native code",
            "module": "flux.jit",
            "tests": "test_jit.py (43 tests)",
            "features": [
                "JITCompiler with inlining",
                "LRU JIT cache (SHA-256 keyed)",
                "Execution tracing (block/call/edge profiling)",
                "Hot path detection",
                "Register allocation (linear scan)",
                "IR optimization passes",
            ],
        },
        {
            "id": "L3_VM",
            "name": "Micro-VM Interpreter",
            "input": "Bytecode",
            "output": "Execution result",
            "module": "flux.vm",
            "tests": "test_vm.py + test_vm_complete.py (108 tests)",
            "features": [
                "Fetch-decode-execute loop",
                "64-register file (16 GP, 16 FP, 16 VEC, 16 system)",
                "Linear region memory model",
                "Condition flags (zero/sign) for CMP-based jumps",
                "10M cycle budget enforcement",
                "Typed exception hierarchy",
                "I/O callback hooks",
                "State dump for debugging",
                "40+ implemented opcodes",
            ],
        },
        {
            "id": "L3_COMPILER",
            "name": "FluxCompiler",
            "input": "Source code (C/Python/FLUX.MD)",
            "output": "Bytecode",
            "module": "flux.compiler",
            "tests": "test_runtime.py, test_integration.py",
            "features": [
                "Multi-language compilation pipeline",
                "Source -> Parser -> FIR -> Optimizer -> Bytecode",
                "Cross-language module linking",
            ],
        },
        {
            "id": "L4_PIPELINE",
            "name": "Full Pipeline",
            "input": "Source / FLUX.MD",
            "output": "Execution result + intermediate artifacts",
            "module": "flux.pipeline",
            "tests": "test_integration.py (14 tests)",
            "features": [
                "End-to-end: FLUX.MD -> Parser -> FIR -> Optimizer -> Bytecode -> VM",
                "PipelineResult with all intermediate results",
                "Polyglot compilation (C + Python merged)",
                "PipelineDebugger with bytecode disassembly",
            ],
        },
        {
            "id": "L4_RUNTIME",
            "name": "Agent Runtime",
            "input": "Bytecode + agent configuration",
            "output": "Agent execution",
            "module": "flux.runtime",
            "tests": "test_runtime.py (6 tests)",
            "features": [
                "Agent (wraps Interpreter)",
                "AgentRuntime orchestrator",
                "Multi-agent support",
                "Trust-gated messaging",
                "CLI (compile/run/test subcommands)",
            ],
        },
        {
            "id": "L5_A2A",
            "name": "Agent-to-Agent Protocol",
            "input": "Agent messages",
            "output": "Coordinated multi-agent execution",
            "module": "flux.a2a",
            "tests": "test_a2a.py",
            "features": [
                "Trust engine (INCREMENTS)",
                "Agent coordination",
                "Message routing",
                "Capability-based security",
            ],
        },
        {
            "id": "L5_PROTOCOL",
            "name": "Communication Protocol",
            "input": "Agent messages",
            "output": "Serialized / routed messages",
            "module": "flux.protocol",
            "tests": "test_protocol.py (85 tests)",
            "features": [
                "4 typed message kinds (Request, Response, Event, Error)",
                "3 channel patterns (Direct, Broadcast, Topic)",
                "Capability-based agent registry",
                "4-step trust handshaking",
                "Binary serialization with batch support",
            ],
        },
        {
            "id": "L6_STDLIB",
            "name": "Standard Library",
            "input": "FIR calls",
            "output": "Runtime function implementations",
            "module": "flux.stdlib",
            "tests": "test_stdlib.py (66 tests)",
            "features": [
                "6 intrinsic functions (print, assert, panic, sizeof, alignof, typeof)",
                "5 collection types (List, Map, Set, Queue, Stack)",
                "6 math functions (min, max, abs, clamp, lerp, sqrt)",
                "6 string functions (concat, substring, split, join, length, format)",
                "3 agent utilities (registry, message queue, task scheduler)",
            ],
        },
        {
            "id": "L6_SECURITY",
            "name": "Security & Capabilities",
            "input": "Agent requests",
            "output": "Authorized / denied",
            "module": "flux.security",
            "tests": "test_security.py",
            "features": [
                "Capability-based security",
                "Sandbox isolation",
                "Resource limits",
            ],
        },
        {
            "id": "L7_COST",
            "name": "Cost Model",
            "input": "Operations",
            "output": "Cost / energy estimates",
            "module": "flux.cost",
            "tests": "test_cost.py",
            "features": [
                "Operation cost estimation",
                "Energy consumption modeling",
            ],
        },
        {
            "id": "L7_RELOAD",
            "name": "Hot Reload",
            "input": "Module changes",
            "output": "Hot-swapped modules",
            "module": "flux.reload",
            "tests": "test_reload.py",
            "features": [
                "Hot code loading",
                "State migration",
            ],
        },
        # ── Extension Layers ──
        {
            "id": "EXT_MODULES",
            "name": "Nested Module System",
            "input": "Module hierarchy",
            "output": "Managed module tree",
            "module": "flux.modules",
            "tests": "test_modules.py (72 tests)",
            "features": [
                "8-level nesting (TRAIN through CARD)",
                "Fractal hot-reload engine",
                "Namespace isolation",
                "SHA-256 checksum trees",
                "Targeted reloads at any granularity",
                "Dependency visualization (reload graph)",
            ],
        },
        {
            "id": "EXT_ADAPTIVE",
            "name": "Adaptive Language Selector",
            "input": "Runtime profiling data",
            "output": "Language assignments per module",
            "module": "flux.adaptive",
            "tests": "test_adaptive.py (99 tests)",
            "features": [
                "5-level heat classification (FROZEN/COOL/WARM/HOT/HEAT)",
                "6 language profiles (Python/TypeScript/C#/Rust/C/C+SIMD)",
                "7-tier scoring (speed, expressiveness, modularity, compile_time, hot_reload, simd, memory_safety)",
                "Cross-language compiler bridge",
                "Bytecode caching with SHA-256 keys",
                "Reload penalty tracking",
            ],
        },
        {
            "id": "EXT_TILES",
            "name": "Tile System",
            "input": "Computation graph",
            "output": "FIR module",
            "module": "flux.tiles",
            "tests": "test_tiles.py (145 tests)",
            "features": [
                "34 built-in tiles across 6 categories",
                "COMPUTE: map, reduce, scan, filter, zip, flatmap, sort, unique",
                "MEMORY: gather, scatter, stream, copy, fill, transpose",
                "CONTROL: loop, while, branch, switch, fuse, pipeline",
                "A2A: tell, ask, broadcast, a2a_reduce, a2a_scatter, barrier",
                "EFFECT: print_effect, log_effect, state_mut",
                "TRANSFORM: cast, reshape, pack, unpack, join, split",
                "DAG composition via TileGraph",
                "FIR emission via blueprints",
                "Registry with fuzzy search",
                "Topological ordering (Kahn's algorithm)",
                "Pattern matching and substitution",
            ],
        },
        {
            "id": "EXT_EVOLUTION",
            "name": "Self-Evolution Engine",
            "input": "System state",
            "output": "Improved system",
            "module": "flux.evolution",
            "tests": "test_evolution.py (154 tests)",
            "features": [
                "Genome (complete system DNA snapshot)",
                "Pattern mining (modified Apriori algorithm)",
                "7 mutation strategies (RECOMPILE_LANGUAGE, FUSE_PATTERN, REPLACE_TILE, ADD_TILE, MERGE_TILES, SPLIT_TILE, INLINE_OPTIMIZATION)",
                "Risk-aware proposals (estimated_risk + estimated_speedup)",
                "Correctness validation with regression detection",
                "Fitness evaluation (speed 0.4 + modularity 0.3 + correctness 0.3)",
                "Multi-generation evolution with convergence detection",
                "9-step cycle: capture -> profile -> mine -> propose -> evaluate -> commit -> measure -> repeat",
            ],
        },
        {
            "id": "EXT_FLYWHEEL",
            "name": "Flywheel Engine",
            "input": "System state",
            "output": "Accelerating improvement",
            "module": "flux.flywheel",
            "tests": "test_flywheel.py (99 tests)",
            "features": [
                "6-phase loop: OBSERVE -> LEARN -> HYPOTHESIZE -> EXPERIMENT -> INTEGRATE -> ACCELERATE",
                "Knowledge base with generalized rules",
                "Parallel experiment execution",
                "Acceleration factor tracking",
                "Self-reinforcing improvement cycle",
            ],
        },
        {
            "id": "EXT_SWARM",
            "name": "Agent Swarm",
            "input": "Agent configurations",
            "output": "Coordinated swarm execution",
            "module": "flux.swarm",
            "tests": "test_swarm.py (102 tests)",
            "features": [
                "5 topologies (mesh, ring, star, tree, full)",
                "Message bus with priority queuing",
                "Deadlock detection",
                "Barrier synchronization",
                "Broadcast, scatter, reduce operations",
                "Swarm evolution (parallel agent specialization)",
                "Topology optimization",
            ],
        },
        {
            "id": "EXT_MEMORY",
            "name": "Persistent Memory",
            "input": "Experiences / observations",
            "output": "Generalized knowledge",
            "module": "flux.memory",
            "tests": "test_memory.py (119 tests)",
            "features": [
                "4-tier persistence (hot/warm/cold/frozen)",
                "Experience recording and generalization",
                "Thompson Sampling for strategy selection",
                "Learning rate adaptation",
                "MutationBandit (multi-armed bandit)",
            ],
        },
        {
            "id": "EXT_SIMULATION",
            "name": "Digital Twin & Simulation",
            "input": "System state",
            "output": "Predictions / what-if results",
            "module": "flux.simulation",
            "tests": "test_simulation.py (112 tests)",
            "features": [
                "Shadow simulation (DigitalTwin)",
                "Performance prediction",
                "Speculative execution (parallel mutation testing)",
                "Decision oracle (ROI-based recommendations)",
                "Chaos testing (fault injection)",
                "Capacity forecasting",
            ],
        },
        {
            "id": "EXT_CREATIVE",
            "name": "Creative Expression",
            "input": "Code / data",
            "output": "Music / art / visualizations",
            "module": "flux.creative",
            "tests": "test_creative.py (146 tests)",
            "features": [
                "Sonification (opcodes -> notes, heat -> dynamics)",
                "Generative art (L-Systems, cellular automata, fractals, reaction-diffusion)",
                "Live coding sessions (undo/redo, tempo sync)",
                "Visualization (ASCII and colored text)",
            ],
        },
        {
            "id": "EXT_SYNTHESIS",
            "name": "System Synthesizer",
            "input": "All subsystems",
            "output": "Unified system",
            "module": "flux.synthesis",
            "tests": "test_synthesis.py",
            "features": [
                "Wires ALL subsystems together",
                "Module hierarchy management",
                "Runtime profiling + adaptive selection",
                "Tile composition",
                "Self-evolution orchestration",
                "Hot-swap API",
                "System reporting (7-section reports)",
            ],
        },
    ],
    "total_tests": 1615,
    "total_modules": 96,
}


def get_architecture_schema() -> dict:
    """Return the full architecture schema."""
    return FLUX_ARCHITECTURE


def get_layer_by_id(layer_id: str) -> Optional[dict]:
    """Look up a single architecture layer by its ID."""
    for layer in FLUX_ARCHITECTURE["layers"]:
        if layer["id"] == layer_id:
            return layer
    return None


def get_module_dependencies() -> dict[str, list[str]]:
    """Return module -> list of modules it depends on.

    This forms a DAG (directed acyclic graph). No cycles.
    """
    return {
        "flux.parser": [],
        "flux.frontend": ["flux.fir"],
        "flux.fir": [],
        "flux.types": ["flux.fir"],
        "flux.bytecode": ["flux.fir"],
        "flux.optimizer": ["flux.fir"],
        "flux.jit": ["flux.fir", "flux.optimizer"],
        "flux.vm": ["flux.bytecode"],
        "flux.compiler": ["flux.fir", "flux.optimizer", "flux.bytecode"],
        "flux.pipeline": ["flux.parser", "flux.fir", "flux.optimizer", "flux.bytecode", "flux.vm"],
        "flux.runtime": ["flux.vm", "flux.compiler", "flux.a2a"],
        "flux.a2a": [],
        "flux.protocol": [],
        "flux.stdlib": ["flux.fir"],
        "flux.security": [],
        "flux.cost": [],
        "flux.reload": [],
        "flux.modules": ["flux.fir"],
        "flux.adaptive": ["flux.fir", "flux.frontend"],
        "flux.tiles": ["flux.fir"],
        "flux.evolution": ["flux.tiles", "flux.adaptive", "flux.modules", "flux.optimizer"],
        "flux.flywheel": ["flux.evolution", "flux.tiles", "flux.adaptive"],
        "flux.swarm": ["flux.a2a", "flux.modules"],
        "flux.memory": [],
        "flux.simulation": ["flux.cost", "flux.evolution"],
        "flux.creative": ["flux.tiles"],
        "flux.synthesis": [
            "flux.modules",
            "flux.adaptive",
            "flux.tiles",
            "flux.evolution",
            "flux.flywheel",
        ],
    }
